name: cookie_collector_bot
description: A little discord bot that lets you collect and do stuff with cookies

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  date_time_format: ^2.0.1
  mysql1: ^0.19.0
  nyxx: 2.0.0-rc.13
  nyxx_commander: 2.0.0-rc.12
  nyxx_interactions: 2.0.0-rc.20
  toml: ^0.11.0
