name: cookie_collector_bot
description: A little discord bot that lets you collect and do stuff with cookies

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  date_time_format: ^2.0.1
  dotenv: ^4.0.1
  mysql_client: ^0.0.27
  nyxx: ^4.1.0
  nyxx_interactions: ^4.3.0
  onyx_chat:
    git: https://github.com/One-Nub/Onyx_Chat.git
