name: cookie_collector_bot
version: 0.0.6
description: A little discord bot that lets you collect and do stuff with cookies
dependencies:
  nyxx:
    path: packages/nyxx/nyxx
  nyxx.commands:
    path: packages/nyxx/nyxx.commands
  safe_config: ^2.0.2
  mysql1: ^0.17.1
dependency_override:
  nyxx:
    path: packages/nyxx/nyxx
