name: cookie_collector_bot
description: A little discord bot that lets you collect and do stuff with cookies

environment:
  sdk: '>=2.9.0-11.0.dev <3.0.0'

dependencies:
  date_time_format: ^1.0.0+4
  mysql1: ^0.17.1
  nyxx: ^1.0.0
  nyxx.commander: ^1.0.0
  yaml: ^2.2.1

dependency_overrides:
  nyxx:
    path: packages/nyxx/nyxx
  nyxx.commander:
    path: packages/nyxx/nyxx.commander
