name: cookie_collector_bot
description: A little discord bot that lets you collect and do stuff with cookies

environment:
  sdk: '>=2.12.0-100.beta <3.0.0'

dependencies:
  date_time_format: ^2.0.1
  mysql1: ^0.17.1
  nyxx: 1.1.0-dev.5
  nyxx_commander: 1.1.0-dev.6
  toml: ^0.10.0

dependency_overrides:
  logging:
    git:
      url: git://github.com/dart-lang/logging.git
